---
all: #Parámetros comunes a todas las plataformas.
  df_fields:
    candles:
      - open
      - high
      - low
      - close
      - volume
  candle_range: 3
  max_workers: 20
  min_strength: 3
  pivot_window: 10
  rsi_period: 14
  report_folder: code/output

bitunix:
  class_name: Bitunix
  api_url: https://openapi.bitunix.com/api/spot/v1
  endpoint:
    candles: 
      path: market/kline/history
      # path: market/kline
      is_dynamic: false
    pairs: common/coin_pair/list
  api_fields:
    candles:
      symbol: str
      open: float
      high: float
      low: float
      close: float
      volume: float
      ts: str
  timeframes: 
    15: 15min
    60: 1h
    240: 4h
    D: 1D
  api_batch: 500
  # api_batch: 201

bitvavo:
  class_name: Bitvavo
  api_url: https://api.bitvavo.com/v2
  endpoint:
    candles: 
      path: candles
      is_dynamic: true
    pairs: markets
  api_fields:
    candles:
      timestamp: int
      open: float
      high: float
      low: float
      close: float
      volume: float
  timeframes: 
    15m: 15min
    1h: 1h
    4h: 4h
    1d: 1D
  api_batch: 1440

kraken:
  class_name: Kraken
  api_url: https://api.kraken.com/0/public
  dynamic_url: false
  endpoint:
    candles: 
      path: OHLC
      is_dynamic: false
    pairs: AssetPairs
  api_fields:
    candles:
      time: int
      open: float
      high: float
      low: float
      close: float
      vwap: float
      volume: float
      count: int
  timeframes: 
    15: 15min
    60: 1h
    240: 4h
    1440: 1D
  api_batch: 721

okx: 
  class_name: Okx
  api_url: https://www.okx.com/api/v5
  dynamic_url: false
  endpoint:
    candles: 
      path: market/candles
      is_dynamic: false
    pairs: public/instruments
  api_fields:
    candles:
      ts: int
      open: float
      high: float
      low: float
      close: float
      volume: float
      volCcy: float
      volCcyQuote: float
      confirm: int
  timeframes: 
    15m: 15min
    1H: 1h
    4H: 4h
    1Dutc: 1D
  api_batch: 300
  pairs_params: 
    instType: SPOT
...